import { contextBridge, ipcRenderer, webUtils } from 'electron'
import { IPC } from '../shared/types'
import type {
  AdvisorStreamEvent,
  AgentStreamEvent,
  EnvEntry,
  OrchestrationEvent,
  PtyDataEvent,
  PtyExitEvent,
  RendererApi,
  ServerLogEvent,
  ServerReadyEvent,
  ServerStatusEvent
} from '../shared/types'

function sub<T>(channel: string, cb: (e: T) => void): () => void {
  const listener = (_: unknown, payload: T): void => cb(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

const api: RendererApi = {
  pickProjectFolder: () => ipcRenderer.invoke(IPC.pickProjectFolder),
  openProject: (path) => ipcRenderer.invoke(IPC.openProject, path),
  getRecentProjects: () => ipcRenderer.invoke(IPC.getRecentProjects),
  createAgent: (input) => ipcRenderer.invoke(IPC.createAgent, input),
  duplicateAgent: (input) => ipcRenderer.invoke(IPC.duplicateAgent, input),
  updateAgent: (agent) => ipcRenderer.invoke(IPC.updateAgent, agent),
  deleteAgent: (agentId) => ipcRenderer.invoke(IPC.deleteAgent, agentId),
  setEdges: (edges) => ipcRenderer.invoke(IPC.setEdges, edges),
  setNodePositions: (positions) => ipcRenderer.invoke(IPC.setNodePositions, positions),
  updateSettings: (patch) => ipcRenderer.invoke(IPC.updateSettings, patch),
  readRole: (agentId) => ipcRenderer.invoke(IPC.readRole, agentId),
  writeRole: (agentId, content) => ipcRenderer.invoke(IPC.writeRole, agentId, content),
  readEnv: () => ipcRenderer.invoke(IPC.readEnv),
  writeEnv: (entries: EnvEntry[]) => ipcRenderer.invoke(IPC.writeEnv, entries),
  readMemory: (agentId) => ipcRenderer.invoke(IPC.readMemory, agentId),
  writeMemory: (agentId, content) => ipcRenderer.invoke(IPC.writeMemory, agentId, content),
  runHeadless: (input) => ipcRenderer.invoke(IPC.runHeadless, input),
  cancelHeadless: (runId) => ipcRenderer.invoke(IPC.cancelHeadless, runId),
  onAgentStream: (cb) => sub<AgentStreamEvent>(IPC.agentStream, cb),
  spawnPty: (input) => ipcRenderer.invoke(IPC.spawnPty, input),
  spawnShell: (input) => ipcRenderer.invoke(IPC.spawnShell, input),
  writePty: (ptyId, data) => ipcRenderer.send(IPC.writePty, ptyId, data),
  resizePty: (ptyId, cols, rows) => ipcRenderer.send(IPC.resizePty, ptyId, cols, rows),
  killPty: (ptyId) => ipcRenderer.send(IPC.killPty, ptyId),
  onPtyData: (cb) => sub<PtyDataEvent>(IPC.ptyData, cb),
  onPtyExit: (cb) => sub<PtyExitEvent>(IPC.ptyExit, cb),
  startRun: (input) => ipcRenderer.invoke(IPC.startRun, input),
  stopRun: (runId) => ipcRenderer.invoke(IPC.stopRun, runId),
  resumeRun: (runId, answer) => ipcRenderer.invoke(IPC.resumeRun, runId, answer),
  onOrchestration: (cb) => sub<OrchestrationEvent>(IPC.orchestration, cb),
  checkAuth: () => ipcRenderer.invoke(IPC.checkAuth),
  listRuns: () => ipcRenderer.invoke(IPC.listRuns),
  loadRun: (file) => ipcRenderer.invoke(IPC.loadRun, file),
  exportTeam: () => ipcRenderer.invoke(IPC.exportTeam),
  importTeamPreview: () => ipcRenderer.invoke(IPC.importTeamPreview),
  importTeamApply: (bundle, path) => ipcRenderer.invoke(IPC.importTeamApply, bundle, path),
  syncToTeam: () => ipcRenderer.invoke(IPC.syncTeam),
  refreshFromTeam: () => ipcRenderer.invoke(IPC.refreshTeam),
  draftRoles: (input) => ipcRenderer.invoke(IPC.draftRoles, input),
  spawnTeam: (input) => ipcRenderer.invoke(IPC.spawnTeam, input),
  applySpawnedTeam: (input) => ipcRenderer.invoke(IPC.applySpawn, input),
  detectManifest: (input) => ipcRenderer.invoke(IPC.detectManifest, input),
  launchServer: (input) => ipcRenderer.invoke(IPC.launchServer, input),
  stopServer: (serverId) => ipcRenderer.send(IPC.stopServer, serverId),
  openProjectPath: () => ipcRenderer.send(IPC.openPath),
  addContext: (paths) => ipcRenderer.invoke(IPC.addContext, paths),
  updateContext: (id, note) => ipcRenderer.invoke(IPC.updateContext, id, note),
  removeContext: (id) => ipcRenderer.invoke(IPC.removeContext, id),
  contextThumbnail: (id) => ipcRenderer.invoke(IPC.contextThumbnail, id),
  addContextPaths: (paths) => ipcRenderer.invoke(IPC.addContextPaths, paths),
  setContextScope: (id, scope) => ipcRenderer.invoke(IPC.setContextScope, id, scope),
  addContextFolder: (paths) => ipcRenderer.invoke(IPC.addContextFolder, paths),
  updateContextFolder: (id, note) => ipcRenderer.invoke(IPC.updateContextFolder, id, note),
  removeContextFolder: (id) => ipcRenderer.invoke(IPC.removeContextFolder, id),
  addPairedDir: (paths) => ipcRenderer.invoke(IPC.addPairedDir, paths),
  setPairedDirWritable: (id, writable) => ipcRenderer.invoke(IPC.setPairedDirWritable, id, writable),
  removePairedDir: (id) => ipcRenderer.invoke(IPC.removePairedDir, id),
  addBackend: (input) => ipcRenderer.invoke(IPC.backendAdd, input),
  updateBackend: (id, patch) => ipcRenderer.invoke(IPC.backendUpdate, id, patch),
  removeBackend: (id) => ipcRenderer.invoke(IPC.backendRemove, id),
  listBackends: () => ipcRenderer.invoke(IPC.backendList),
  setBackendToken: (id, token) => ipcRenderer.invoke(IPC.backendSetToken, id, token),
  backendEncryptionAvailable: () => ipcRenderer.invoke(IPC.backendEncryptionAvailable),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  listSkills: () => ipcRenderer.invoke(IPC.listSkills),
  listResumable: () => ipcRenderer.invoke(IPC.listResumable),
  discardRun: (runId) => ipcRenderer.invoke(IPC.discardRun, runId),
  gitInfo: () => ipcRenderer.invoke(IPC.gitInfo),
  gitCheckout: (branch: string) => ipcRenderer.invoke(IPC.gitCheckout, branch),
  sendAdvisor: (input) => ipcRenderer.invoke(IPC.advisorSend, input),
  onAdvisorStream: (cb) => sub<AdvisorStreamEvent>(IPC.advisorStream, cb),
  cancelAdvisor: (turnId) => ipcRenderer.send(IPC.advisorCancel, turnId),
  pickAdvisorFolder: () => ipcRenderer.invoke(IPC.advisorPickFolder),
  onServerLog: (cb) => sub<ServerLogEvent>(IPC.serverLog, cb),
  onServerStatus: (cb) => sub<ServerStatusEvent>(IPC.serverStatus, cb),
  onServerReady: (cb) => sub<ServerReadyEvent>(IPC.serverReady, cb)
}

contextBridge.exposeInMainWorld('api', api)
